# Generated by Django 3.2.18 on 2023-12-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_room',
            new_name='chatroom',
        ),
    ]
