# Generated by Django 3.2.6 on 2023-12-07 14:08

import chat.entity.chat_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(blank=True, max_length=455, null=True, upload_to=chat.entity.chat_models.attachment_location)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_attachment', to='chat.message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
