# Generated by Django 3.2.6 on 2023-12-07 15:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20231206_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="User's Phone Number", max_length=128, null=True, region=None, unique=True),
        ),
    ]
